### ISSUE TITLE
Allow to exclude images from lazyloading

### ISSUE THREAD

**Issue by thesec** [FriendsOfShopware/FroshPlatformThumbnailProcessor#75]
### Please describe the feature you would like to see implemented.

https://web.dev/lcp-lazy-loading/ and actual results suggest a gain on LCP when not lazyloading images above the fold.

Instead of fiddling with mechanisms to identify affected elements I suggest to allow to explicitely exclude images such as e.g. logo, navigation icons and jumbo header backgrounds.

The easiest way to do so might be adding a speaking CSS classname of 'nolazyload'.

Looking into the lazysizes' JS I did not find an option to do so.
Also the thumbnail's twig left me without an idea as the media management I am familiar with in Shopware's backend does not allow to add classes to be assigned the image.

Even if it is not something you would consider to add right away a hint in a possible direction of where to add this would be appreciated :)

Thank you in advance.

**Comment by tinect** [comment]
Hey, this would just work, if there is no need for any thumbnail because:

lazysizes (JS) makes lazyLoading AND calculates the needed size (see attribute sizes) to be loaded by the browser.
While this isn't available initially, there is possibility to use thumbnails for such functions.

So, you would end up with loading the biggest image. Sure, for logo is would work, but the more important and influencing content would load too big images. That's the reason, I don't see any `good` way and solution to get lower LCP, too :-(

**Comment by thesec** [comment]
Swift as always.  Thank you.

A naming pattern to look after in the `media.url` should work to build a toggle.
